name: Manual Deploy API

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Archive dist and node_modules
        run: |
          tar -czf dist.tar.gz dist node_modules package.json tsconfig.json tsconfig.build.json

      - name: Write SSH key
        run: |
          echo "$SSH_KEY" > key.pem
          chmod 600 key.pem
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}

      - name: Upload to server via SCP
        run: |
          scp -i key.pem -o StrictHostKeyChecking=no dist.tar.gz ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/www/video-meme-tool-api/dist.tar.gz

      - name: Clean up
        run: rm -f key.pem